### ISSUE TITLE
Un repo par projet ?

### ISSUE THREAD

**Issue by 0x6A6F7368** [LeniBard/IRC#1]
Il serait peut être bon de créer un repo' par projet ?
Ça risque d'être rapidement le chaos à contrario.

**Comment by Diagamma** [comment]
Boh, on verra bien, si ça marche pas on fera ça. (c'est qui au fait ?)

**Comment by Pyraah** [comment]
Hmm pour l'instant je vais éviter de balancer les sources de QYou sur le net tant que je ne suis pas satisfait (il manque la masse de features avant d'être utilisable par le quidam).
